### ISSUE TITLE
Playlists not showing up in playlist tags page

### ISSUE THREAD

**Issue by ianrispin** [Bergbok/Spicetify-Creations#6]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663.gb699649e
- Spicetify version: v2.36.8
- MacOS Sonoma 14.2.1
```

### 📝 Description

I can add and view tags on playlists, and I can see all my tags listed at the top of the playlist tags page, but no playlists show up on the page, regardless of whether zero, one, or multiple tags are selected. The same for both the Search and "All Tagged Playlist" tabs. There do not appear to be any related errors in the console.

### 📸 Screenshots

https://github.com/Bergbok/Spicetify-Creations/assets/50210259/d99e3a0a-d0ce-49b8-8a14-9cd86ae37119

**Comment by Bergbok** [comment]
I'm aware of this but I'm not sure how to fix it to be honest.
Started happening after some recent updates.
I'm hoping it's something that can be fixed by a Spicetify update.

In the meantime, even though you can't see the playlists, the play/shuffle functionality should still work.

I already opened a [issue ](https://github.com/harbassan/spicetify-apps/issues/87) on the repo I got the card component code from.
