### ISSUE TITLE
Add "All Untagged Playlists" page

### ISSUE THREAD

**Issue by ianrispin** [Bergbok/Spicetify-Creations#8]
### 📝 Provide a description of the new feature

Add a setting in the "mass tagging" section to add an "untagged" tag to playlists with no tags (perhaps with the option to change the name of the tag).

### ➕ Additional Information

My reason for wanting this feature is to keep track of the playlists I've recently created on my phone or those that I just haven't got around to tagging yet. An alternative solution to this could be to add a section in the tags page/screen with all the playlists that have no tags.

**Comment by Bergbok** [comment]
Great idea, makes a lot of sense. I'll look into implementing it.

_Regarding https://github.com/Bergbok/Spicetify-Creations/issues/4, don't worry I didn't forget about it - it's been in the back of my mind. Started working on it, but had to move houses and just haven't gotten back into working on it since._
